# Generated by Django 4.1.7 on 2023-06-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_order_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sender',
        ),
    ]
