# Generated by Django 4.1.7 on 2023-06-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_order_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_phone',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
    ]
