# Generated by Django 4.1.7 on 2023-04-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='portfolio/%Y/%m/%d/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='portfolio/%Y/%m/%d/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='portfolio/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('top_sales', models.ManyToManyField(blank=True, to='portfolio.top')),
            ],
        ),
    ]
