# Generated by Django 4.1.7 on 2023-04-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
