# Generated by Django 4.1.7 on 2023-04-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_works_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
